service: password-generator-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: sa-east-1
  memorySize: 256
  timeout: 10
  environment:
    RECAPTCHA_SITE_KEY: ${env:RECAPTCHA_SITE_KEY}
    RECAPTCHA_API_KEY: ${env:RECAPTCHA_API_KEY}
    RECAPTCHA_PROJECT_ID: ${env:RECAPTCHA_PROJECT_ID}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://password-ui.vercel.app
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

package:
  individually: true
  patterns:
    - dist/**
